-- Chạy file này trong phpMyAdmin (chọn database "starfly" -> tab SQL -> dán vào -> Go)
USE starfly;

INSERT INTO movies (title, year, genre, rating, description, poster, backdrop, trailer) VALUES
('Interstellar', 2014, 'Sci-Fi', 8.7, 'Khi Trái Đất dần trở nên không thể sinh sống, một nhóm phi hành gia bắt đầu hành trình xuyên qua không gian để tìm kiếm một ngôi nhà mới cho nhân loại.', 'https://image.tmdb.org/t/p/w500/gEU2QniE6E77NI6lCU6MxlNBvIx.jpg', 'https://image.tmdb.org/t/p/original/gEU2QniE6E77NI6lCU6MxlNBvIx.jpg', 'https://www.youtube.com/embed/zSWdZVtXT7E'),
('Dune: Part Two', 2024, 'Sci-Fi', 8.6, 'Paul Atreides đoàn tụ với Chani và người Fremen trong chuyến hành trình báo thù cho gia đình và định mệnh.', 'https://image.tmdb.org/t/p/w500/1pdfLvkbY9ohJlCjQH2CZjjYVvJ.jpg', 'https://image.tmdb.org/t/p/original/1pdfLvkbY9ohJlCjQH2CZjjYVvJ.jpg', 'https://www.youtube.com/embed/Way9Dexny3w'),
('Oppenheimer', 2023, 'Thriller', 8.6, 'Câu chuyện về J. Robert Oppenheimer và những lựa chọn làm thay đổi mãi mãi thế giới hiện đại.', 'https://image.tmdb.org/t/p/w500/8Gxv8gSFCU0XGDykEGv7zR1n2ua.jpg', 'https://image.tmdb.org/t/p/original/8Gxv8gSFCU0XGDykEGv7zR1n2ua.jpg', 'https://www.youtube.com/embed/uYPbbksJxIg'),
('The Batman', 2022, 'Action', 7.8, 'Batman lần theo những manh mối đen tối giữa lòng Gotham và chạm đến một âm mưu sâu hơn anh tưởng.', 'https://image.tmdb.org/t/p/w500/74xTEgt7R36Fpooo50r9T25onhq.jpg', 'https://image.tmdb.org/t/p/original/74xTEgt7R36Fpooo50r9T25onhq.jpg', 'https://www.youtube.com/embed/mqqft2x_Aa4'),
('Spider-Man: No Way Home', 2021, 'Action', 8.2, 'Khi danh tính bị tiết lộ, Peter Parker phải đối mặt với những vị khách đến từ các vũ trụ khác.', 'https://image.tmdb.org/t/p/w500/1g0dhYtq4irTY1GPXvft6k4YLjm.jpg', 'https://image.tmdb.org/t/p/original/1g0dhYtq4irTY1GPXvft6k4YLjm.jpg', 'https://www.youtube.com/embed/JfVOs4VSpmA'),
('John Wick: Chapter 4', 2023, 'Action', 7.6, 'John Wick khám phá con đường đánh bại High Table và giành lại tự do trong trận chiến cuối cùng.', 'https://image.tmdb.org/t/p/w500/vZloFAK7NmvMGKE7VkF5UHaz0I.jpg', 'https://image.tmdb.org/t/p/original/vZloFAK7NmvMGKE7VkF5UHaz0I.jpg', 'https://www.youtube.com/embed/qEVUtrk8_B4'),
('Your Name', 2016, 'Anime', 8.8, 'Hai người trẻ ở hai nơi xa xôi bất ngờ hoán đổi cơ thể và cùng tìm kiếm sợi dây kết nối định mệnh.', 'https://image.tmdb.org/t/p/w500/q719jXXEzOoYaps6babgKnONONX.jpg', 'https://image.tmdb.org/t/p/original/q719jXXEzOoYaps6babgKnONONX.jpg', 'https://www.youtube.com/embed/xU47nhruN-Q'),
('A Quiet Place', 2018, 'Horror', 7.5, 'Một gia đình phải sống trong im lặng tuyệt đối để tránh những sinh vật săn mồi bằng âm thanh.', 'https://image.tmdb.org/t/p/w500/nAU74GmpUk7t5iklEp3bufwDq4N.jpg', 'https://image.tmdb.org/t/p/original/nAU74GmpUk7t5iklEp3bufwDq4N.jpg', 'https://www.youtube.com/embed/WR7cc5t7tv8'),
('Deadpool & Wolverine', 2024, 'Action', 7.6, 'Deadpool hợp tác với Wolverine trong một nhiệm vụ xuyên đa vũ trụ đầy hỗn loạn.', 'https://image.tmdb.org/t/p/w500/8cdWjvZQUExUUTzyp4t6EDMubfO.jpg', 'https://image.tmdb.org/t/p/original/8cdWjvZQUExUUTzyp4t6EDMubfO.jpg', 'https://www.youtube.com/embed/73_1biulkYk'),
('Inside Out 2', 2024, 'Comedy', 7.6, 'Riley bước vào tuổi thiếu niên, nơi những cảm xúc mới xuất hiện và làm đảo lộn mọi thứ.', 'https://image.tmdb.org/t/p/w500/vpnVM9B6NMmQpWeZvzLvDESb2QY.jpg', 'https://image.tmdb.org/t/p/original/vpnVM9B6NMmQpWeZvzLvDESb2QY.jpg', 'https://www.youtube.com/embed/LEjhY15eCx0'),
('Past Lives', 2023, 'Romance', 7.8, 'Hai người bạn thời thơ ấu gặp lại nhau sau nhiều năm và nhìn lại những lựa chọn của đời mình.', 'https://image.tmdb.org/t/p/w500/k3waqVXSnvCZWfJYNtdamTgTtTA.jpg', 'https://image.tmdb.org/t/p/original/k3waqVXSnvCZWfJYNtdamTgTtTA.jpg', 'https://www.youtube.com/embed/kA244xewjcI'),
('The Super Mario Bros. Movie', 2023, 'Comedy', 7.0, 'Mario và Luigi rơi vào một thế giới kỳ lạ và bắt đầu cuộc phiêu lưu lớn nhất đời mình.', 'https://image.tmdb.org/t/p/w500/1f3qspv64L5FXrRy0MFgXqB6hIh.jpg', 'https://image.tmdb.org/t/p/original/1f3qspv64L5FXrRy0MFgXqB6hIh.jpg', 'https://www.youtube.com/embed/TnGl01FkMMo');
